### ISSUE TITLE
輸入完驗證碼後，無法進下一步...

### ISSUE THREAD

**Issue by bluefatcat1993** [dsync5566/tixCraftSupport#5]
近期發現，輸入完驗證碼後，無法進入下一步了，跪求更新啊～

**Comment by dsync5566** [comment]
現在使用應該沒問題。在七月的時候有修改過驗證方法?

**Comment by bluefatcat1993** [comment]
目前是能正常使用了
七月有沒有修改過驗證方法，我不清楚...

只不過有個小問題...
我下載原碼並修改成自己喜歡的設定介面配色，然後發現到有個錯誤...

圖：https://i.imgur.com/9hNkdYf.png

----------
另外，我剛剛有將我自己 DIY 修改的東西也分享上去了，可以看一下～
還缺兩張圖 Icon 和 設定頁面背景圖
https://i.imgur.com/PJ0eYSR.png
https://i.imgur.com/4Nw8n9n.jpg

**Comment by dsync5566** [comment]
"manifest_version" 的設定在2023年1月後就需要改為3
會有幾個設定不相容，所以需要再研究一下。
